name: CD PHP Login

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nome do reposit칩rio que acionou o CD'
        required: true
        default: 'Pgabriel2605/logiin-php'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do reposit칩rio que acionou o CD
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repo_name }}
        token: ${{ secrets.REPO_PAT }}   # Use seu PAT aqui hidcwchcwdvsucdwbhdwchcsbvc\ssbschjdssdbhshbhbdcsbhjhjdhjewui
        ref: master                     # Ajuste para 'main' se necess치rio

    - name: Simular Deploy
      run: |
        echo "Realizando deploy do reposit칩rio ${{ github.event.inputs.repo_name }}..."
        echo "Deploy realizado com sucesso!"
