name: CI Reutilizável PHP Login

on:
  workflow_call:
    inputs:
      php-version:
        description: 'Versão do PHP'
        required: true
        type: string
    secrets:
      REPO_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-mbstring
          echo "Dependências instaladas."

      - name: Rodar testes
        run: |
          echo "Rodando testes..."
          php -l index.php

      - name: Build do projeto
        run: |
          echo "Build realizado com sucesso!"

      - name: Deploy (simulado)
        run: |
          echo "Deploy simulado concluído!"
